### ISSUE TITLE
Question: Using limit() on a collection with thousands of documents

### ISSUE THREAD

**Issue by AlcuinGuest** [geofirestore/geofirestore-js#104]
Big fan of the library!

I want to implement a large search radius (100's of kms) on a large collection of small-medium documents (1000's of documents). 

I see there are limitations to using limit, but I want to double check. If I limit(100), will Firebase still log 1000's of read requests because geofirestore applies the limit on the client? 

If so, is there any way around this? Any alternatives I could use that will limit on the request? 

Thanks!

**Comment by MichaelSolati** [comment]
You shouldn't get thousands of read requests. A query counts as a read, and a query can have many documents. Usually a geoquery makes 9ish read requests, so you'll still get the 9 reads each one querying 1000 docs, and on the client we filter through the 9 requests finding the 1000 closest docs and only return those.

Unfortunately there is no way around this... The geofirestore (and geofire) libraries wraps/scans hashes around the hash of what/where you select. That way if you're point is by the borderline of where a hash could be we don't miss areas right outside of the query. So if we're doing multiple queries in order to ensure that we have the full area covered then we will hit the ref.limit for each query (which will obvs be more than the initial x that you wanted).

**Comment by andy-t-wang** [comment]
So I'm a little confused. Lets say in a 50 mile radius I have 1000 documents that match. Does limit improve performance at all?

**Comment by MichaelSolati** [comment]
@andy-t-wang it could, it likely will not. 

Consider a geoquery is a composition of multiple queries, now imagine you want to limit your results to 100 items, each of the queries (lets say there would be 9) will now be limited to 100 items. As a result the geoquery will at most query 900 items queried, and the closest 100 of those 900 (unless the total is less than 100) will be returned to you.

This may provide a performance improvement if those multiple queries could/would bring in over 100 items.
