### ISSUE TITLE
Max value of radius that can be applied?

### ISSUE THREAD

**Issue by iwantooxxoox** [geofirestore/geofirestore-js#109]
Hi, Thanks for the great library.

Two questions for you.

1. What is the maximum value of "radius" that we can apply? I store a document 12000km away from the center, and set the radius to 15000, it turns out that document is not listed in the response, but other documents within 1000km are.

2.  Is it possible to query documents with "center" but without "radius"? what I want to do is to query all documents from the collection with distance.

Thanks.

**Comment by MichaelSolati** [comment]
1) Reasonably the max radius would be [6,371](https://www.google.com/search?q=radius+of+the+earth+in+km) (as that is the radius of the earth). However the library applies no limits, there are some inherent limitations to geohash queries though so that may be the problem you're facing

2) You can not do a `near` query without a radius and a center. If you want to query all documents, then you don't need a geoquey... just right a basic query like this:

```TypeScript
// Create a Firestore reference
const firestore = firebase.firestore();

// Create a GeoFirestore reference
const geofirestore: GeoFirestore = new GeoFirestore(firestore);

// Create a GeoCollection reference
const geocollection: GeoCollectionReference = geofirestore.collection('restaurants');

// Create a GeoQuery based on a location
const query: GeoQuery = geocollection;

// Get query (as Promise)
query.get().then((value: GeoQuerySnapshot) => {
  console.log(value.docs); // All docs returned by "GeoQuery"
});
```

**Comment by iwantooxxoox** [comment]
Thanks for the prompt reply @MichaelSolati, you're awesome.

I still don't quite understand the meaning of "radius", I thought radius means the distance from the "center", so the maximum radius would be half of Earth's circumference, which is 40,075/2. So that we can query any location of Earth from any designated center. 
Also I'd love to know more about "limitations to geohash queries", if you have time to share.

Thanks.
