### ISSUE TITLE
Getting distance null in the return object

### ISSUE THREAD

**Issue by shekhars-realm** [geofirestore/geofirestore-js#131]
here is the return object: 

 [ { exists: true,
    id: 'VXgVXlvwLVXAFKDifcOKq',
    data: [Function: data],
    distance: null } ]

Any possible reasons!

**Comment by MichaelSolati** [comment]
Can I see your query? If it isn't a geoquery then distance will be null.

**Comment by shekhars-realm** [comment]
sure.

geofirestore.collection('events').near({ center: new admin.firestore.GeoPoint(49.444231, 7.699167), radius: 1.5 }).get().then(data => {
    console.log('data: ',data.docs);
  })

the data structure is same as suggested in the docs.

**Comment by MichaelSolati** [comment]
The distance should work just fine, I created a sample stackblitz example showing how to access distance here => https://stackblitz.com/edit/geofirestore-distance

I'd advise starting to look at line 32, and if your code looks like that and still doesn't work then it is likely an issue with how the data is stored. Geofirestore works with data added to a collection by geofirestore, so it's good to be familiar with [what that looks like](https://github.com/geofirestore/geofirestore-js/tree/v3.3.1#data-structure).

![Screen Shot 2019-07-29 at 3 34 27 PM](https://user-images.githubusercontent.com/11811422/62087721-98db1f80-b217-11e9-9692-b97c00e505e3.png)

Since I can not replicate this, I'm closing the issue, however if you can provide sample code and a screenshot example of a document in a collection we can go from there!

**Comment by MichaelSolati** [comment]
PS, the distance will be null if the `l` field is not a proper GeoPoint. While you never see the `g` or `l`, only the content of the `d`, geofirestore needs them to work properly.

**Comment by shekhars-realm** [comment]
Hey, sorry for the later reply.

I guess there is some problem in the way I am storing the data: 

![firebase](https://user-images.githubusercontent.com/34271274/63697766-cec2f200-c81d-11e9-828d-f53e2c3499d1.PNG)

**Comment by shekhars-realm** [comment]
I am using l for sorting the data, not locationString

**Comment by Todmy** [comment]
For me distance returns as null if I didn't set radius property
