### ISSUE TITLE
Cloud functions: Inequality filter error after near call

### ISSUE THREAD

**Issue by rodduenes** [geofirestore/geofirestore-js#150]
Hello! I found an interesting issue. I have the following compound query:

`collection.where('startTime', '>=', fromTime).where('startTime', '<', toTime);`

After deploying my cloud functions, I can make this call multiple times and it works as expected. If I make a `collection.near(...)` call, the compound query stops working with the following error:

`Error: 3 INVALID_ARGUMENT: inequality filter property and first sort order must be the same: d.startTime and g`

If I redeploy the cloud functions the behavior repeats: it works until I make the near call.

As an extra note, this doesn't happen when I emulate the cloud functions on my machine while still connecting to the same remote Firestore.

I'm using geofirestore v3.3.1

Thanks!

**Comment by rodduenes** [comment]
I opted to split my collections and use the geofirestore collection exclusively for the `near` operation to address my issue. Is this the intended usage or are there plans to support the above in the future? Thank you for your great work!

**Comment by MichaelSolati** [comment]
Hey @rodduenes, so yea you can't have inequality filters with geofirestore as geofirestore uses inequality filters in order to make a query and firestore doesn't support multiple inequalities. See the [README.md](https://github.com/geofirestore/geofirestore-js/tree/v3.3.1#limitations--considerations) as well as [this response](https://github.com/geofirestore/geofirestore-js/issues/78#issuecomment-456218233) to a similar issue.

**Comment by rodduenes** [comment]
Thanks @MichaelSolati, clearly I missed that while reading the readme before
