### ISSUE TITLE
Too many reads

### ISSUE THREAD

**Issue by barakoles** [geofirestore/geofirestore-js#151]
Hi guys... I've been using this library but I'm having a quite odd result when I check my usage, if someone could explain this to me ways on how can I make it a bit more efficient I'd appreciate.

Right now I use `onSnapShot` for a collection of around 50 documents (I then used `limit` to limit those down to 20) 
It might be something wrong or something that I forgot to apply on my react application such as unmounting (or something similar) the component but in a 2 hour usage of development It got into a number of 2k reads that I can see on the firebase console. (I'm using other reads as well but these are very minimal)

Thanks!

**Comment by MichaelSolati** [comment]
So the `limit` wouldn't really have a significant impact on limiting the document reads. As documented, limit happens client side. So if the geoquery collects more docs than needed it'll sort them by closest to furthest and then cut off excess documents.

The reason for this is a geoquery is actually 8(ish) regular queries based on different geohashes that cover the area of your query. Because we combine all the queries on the client, we can't really apply a helpful limit. The limit is applied to each of the combined queries. But if there are hypothetically 8 queries used to cover the area you're trying to search, a limit of 20 would be applied to each query (because there's a possibility that one of those queries would return no documents).

So hypothetically if it requires 8 geohashes to query the area you want to cover, and you're only looking for 20 documents, we could read anywhere from 0 to 160 documents.

The limit can help keep doc reads down, but only marginally.

I do think that 2k in 2 hours of development makes sense. `onSnapshot` is a listener waiting for updates, which leads to new doc reads when a doc changes. If you're in dev mode, your rebuilds are triggering new reads as well.

If I could give some thoughts to help lower the read count, consider using Firestone caching and the get method.

**Comment by barakoles** [comment]
@MichaelSolati Thanks for the explanation, man. I've made some changes, like the one you said (using the get method), and will look into using Firestore caching, but as a quick solution I implemented a localStorage property to check if it will have to fetch or not. It already lowered the count significantly. Thanks. Now, for security purposes, do you know if there's a way to add a security rule for the user to limit it's reads to the database somehow?
