### ISSUE TITLE
Does the new introduction of "array-contains-any" and "in" help with pagination using geofirestore.

### ISSUE THREAD

**Issue by jerryheir** [geofirestore/geofirestore-js#161]
With the introduction of some of these new features, can we as users of geofirestore hope that our dream of pagination is soon on the horizon.

**Comment by MichaelSolati** [comment]
I'm not really sure how these new queries would allow for pagination. The issue faced with `geofirestore` is the compounding of different geohashes that will cover the radius/area you a user queries as well as a little extra (because of how we're using basically a bunch of squares to cover a circle).

Because we can't run a sort on the query on the server, the sort has to happen on client, I don't see this working. I'm gonna close this, but if you have an idea as to how that would work I'd love to hear it! (and I can reopen this)
