### ISSUE TITLE
Querying radius with no entities inside doesn't return snapshot

### ISSUE THREAD

**Issue by Len-art** [geofirestore/geofirestore-js#73]
Example:
```
const geoFireStore = new GeoFirestore(firestore)
geoFireStore.collection('myCollection')
            .near({ center, radius })
            .onSnapshot((snapshot) => console.log(snapshot))
```

If there's no entities inside the circle, I don't get the snapshot because callback never gets called. Firestore usually returns a snapshot, with an `empty` property set to `true`.

**Comment by MichaelSolati** [comment]
Hey @Len-art, a few small things...

1) Did you add your data to your collection with geofirestore? This doesn't query regular collections as we need to cook data in order to make things work.

2) Which version of geofirestore are you using?

3) Can you make a stackblitz? The code looks right, and should work. So I need to see more to figure out what's going on.

**Comment by Len-art** [comment]
Hey, thanks for writing this response to me, now let me answer your questions three:

1. Yes, the query works just great as long as there are entities inside the queried circle. When I move the query to an empty position I stop getting the snapshots. Mind you, if I use `get` i always get the response, but with `onSnapshot` i only get a response if the query is not empty. Stackblitz example has both methods, for easier comparison.
2. I'm using 3.0.1.
3. Of course, just did: https://stackblitz.com/edit/react-docpqf

**Comment by MichaelSolati** [comment]
Oooh, this IS a unique issue then. I'll have to look into this over the next few days. (Probably today)

**Comment by EskelCz** [comment]
@MichaelSolati I'm seeing the same issue in 3.3.1, is it possible? No snapshot call when there is no result.

Also, is it possible to change the location of the query, when my location changes? (So I get change.type 'removed' when someone becomes too far for the query radius)
I know I can make a new query but then I have to compare changes myself, so that markers on map are smoothly translated, instead of just redrawn.
