### ISSUE TITLE
How to add document without the coordinates key?

### ISSUE THREAD

**Issue by Annihil** [geofirestore/geofirestore-js#84]
When adding a document to a geocollection like this
```js
geocollection.add({
    xxx: 'yyy',
    coordinates: new firebase.firestore.GeoPoint(51.5108272, -0.0770001)
});
```
Since the GeoDocument structure is the following
```ts
interface GeoDocument {
    g: string;
    l: GeoPoint;
    d: DocumentData;
}
```
![](https://i.imgur.com/mEtkQi2.png)
`l` and `coordinates` are redondant, is it possible to delete `coordinates` key of the document while adding it to the collection, or add another parameter to the `add` function to pass a GeoPoint to specify the coordinates?

**Comment by MichaelSolati** [comment]
So the redundancy is necessary. We need a GeoPoint in order to encode a geohash, which we query, and we use the GeoPoint for some calculation and validation under the hood (as geohashes aren't accurate). Ok, so we have explained why it's necessary at the top level.

Now going into the `d` level, that's your data, and you'll likely need to have the GeoPoint as a reference to the location. Now we could just pass back the `l` field, however we don't want to really touch any of your data in the `d` field. Also, the library allows you to mark any field as the GeoPoint, not just the coordinates field. That can be used as the [second argument of the `add` method](https://geofirestore.com/classes/_geocollectionreference_.geocollectionreference.html#add).

So with these considerations in mind this was the solution we/I opted for.

**Comment by Annihil** [comment]
While converting the document, why not deleting the `coordinates` key thought?
It's not needed anymore

**Comment by MichaelSolati** [comment]
We don't want to touch the users data though. There also isn't any real benefit to this (I'm not sure why this would be a feature)

**Comment by Annihil** [comment]
```js
geocollection.add({
    xxx: 'yyy'
},
{lat: 51.5108272, lng: -0.0770001});
```
would be cleaner I believe

**Comment by MichaelSolati** [comment]
I don't think this would be the right direction for the library, and I can not think of a good reason to support this. However with transactions going to be supported in the very near future you could handle this with a simple function like this...

```
export class StripDocument {
  constructor(private _db: GeoCollectionReference) {}

  public add(doc: any, coordinates: firebase.firestore.GeoPoint) {
    const ref = this._db.doc();
    return this._db.firestore.runTransaction((transaction: firebase.firestore.Transaction) => {
      const geotransaction = new GeoTransaction(transaction);
      return geotransaction.get(ref).then(() => {
        geotransaction.set(ref, {...doc, coordinates});
        transaction.set(ref['_document'] as firebase.firestore.DocumentReference, doc);
        return Promise.resolve(true);
      });
    });
  }
}
```

As mentioned GeoTransactions aren't out yet, hopefully by the end of the weekend. But this class/function should work for you when it is out (I didn't test it, I just threw it together quickly... It may need some tweaking)

**Comment by JorgeMoralesLopez** [comment]
So would it be possible to remove or not add coordinates in documentData?
I want to have the least possible data in documentData and since in the geopoint we have the coordinates, would it be possible?

**Comment by fabyeah** [comment]
I have the same issue. Didn't see this when I created mine #181.
